tari-project/tari_utilities

Cargo.toml
src/hex.rs

Many unicode characters are more than 1 byte long (e.g. emoji). If one
tries to take a slice on a string containing such characters that
would otherwise 'break' the character, a panic is thrown.
The `from_hex` function had a bug that checked if the first 2 cahrs of a
string are '0x' when converting from string to a byte string. Passing an
emoji to this function would cause a panic.
Since any non-ascii characters aren't valid hexadecimal anyway, we can
check that all characters are actually ascii before doing any slice
checks.
A test was added that catches this case and confirms that the bug is
fixed.

Catch unicode hex error

---

Cargo.toml
src/byte_array.rs
src/hex.rs

There's no need for an associated type in the hex trait; the
`from_hex` method should just return `Self`

Refactor Hex to remove associated type

---

src/bit.rs
tests/mod.rs

This PR changes the `bits_to_uint` function to check for attempt to shift with overflow. 
This is a breaking change and would require a new version of the crate published, and the related code updated in the Tari repo on upgrade. 
Added some test cases. Related to #9 - I think these 2 PRs should be merged and use the same approach, both should rename the functions and return options.
Issue details: 
A shift left overflow can be triggered inside the bits_to_uint function.
This overflow is triggering a panic if the code is compile in debug mode (overflow-checks compiler flag) and it will be completely silent if the code is compiled in release mode.
Details:
found by @pventuzelo
found using fuzzing
related code (bits_to_uint): https://github.com/tari-project/tari_utilities/blob/da015a3c5b0a00 …

[fuzzing] Change `bits_to_uint` to check for shift overflow

---

src/bit.rs

- Adds checked_uint_to_bits, that returns None if the bit_count > 32 or
64 (depending on architecture). This prevents an overflow on the
shift-left operation and allows the caller to decide on how they want to deal with it.
- ~~Deprecates~~ removes uint_to_bits (breaking change).
- ~~uint_to_bits panics if the bit_count is large in release mode~~
(previously only debug)
- Added basic tests
Tari usage: this function is only used with bit_count 11, so in this case it can safely use unwrap on the checked version
Issue found by @the-mog
related code: https://github.com/tari-project/tari/blob/c58a7e53c409cd90ec319c70410aabd477f3f8ed/base_layer/mmr/src/common.rs#L36

Add checked_uint_to_bits, remove uint_to_bits

---

src/byte_array.rs
src/hex.rs

`Hex::to_hex` now converts the given byte slice to hex directly instead
of converting a copy of the data (allocated on the heap).
`to_hex` now reserves the required memory for the string once
potentially saving on additional allocations.

Removed unnecessary heap allocation in Hex::to_hex

---

.github/workflows/pr_title.yml
src/bit.rs

This PR adds a lint check for pull request titles to ensure they conform to the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
This will help ensure that these follow the same convention across repositories.
This has been carried over from https://github.com/tari-project/tari.

ci: add pull request title check

---

src/fixed_set.rs

Add `FixedSet::iter()` to allow iterating without cloning elements.
This is a zero copy and allocation alternative to 
```rust
set.clone().into_vec().iter()....
```

feat: add expose by ref iterator for FixedSet

---

Cargo.toml
src/epoch_time.rs

`chrono` crate uses `time` internally, but it's not actively maintained and we should prefer to use `time` crate directly.
There is at least one known security issue in `chrono`: https://github.com/chronotope/chrono/issues/602

feat: add time crate support

---

Cargo.toml

This fix removes implicit usage of the outdated `time` (1.43.0) crate.

fix: avoid implicit time dependency

---

src/byte_array.rs

Removes an unnecessary heap allocation in to_hex

fix(byte_array): remove unnecessary allocation in to_hex

---

.versionrc.json
scripts/bump-version
scripts/cargo-version-updater.js

Adds script using `standard-version` to bump versions in Cargo.toml and update changelog
`./scripts/bump-version`
**prereleases**
`./scripts/bump-version --prerelease rc`
https://github.com/conventional-changelog/standard-version#cli-usage

feat: adds script for standard-version

---

README.md
src/hidden.rs
src/lib.rs

Description
---
Adding a wrapper type to mask sensitive data in debug, and log output.
Motivation and Context
---
To reduce attack vector surface area by ensuring log data doesn't contain private information.
How Has This Been Tested?
---
With a single test. It has not yet been applied in practice.

feat: hidden type to mask sensitive data in logs

---

src/byte_array.rs

This PR implements `ByteArray` for all types of byte arrays.
For example, `EncryptedValue` has 24 bytes size, using this patch we could get rid of implementing the `ByteArray` trait manually.

feat: implement ByteArray for byte arrays of all sizes

---

Cargo.toml
deny.toml
src/hidden.rs
src/lib.rs
src/password.rs
src/serde/hex.rs

The PR introduces a special wrapper for passphrases that guarantees the data will be erased when value dropped.
Notes:
- `unicode-ident` dependency adds extra `Unicode-DFS-2016` license since `1.0.2`: https://crates.io/crates/unicode-ident/versions
-  The license added to our list of allowed licenses (`deny.toml`), because `Unicode-DFS-2016` is approved by OSI: https://opensource.org/node/1077

feat: add SafePassword struct

---

src/password.rs

Signed-off-by: Andrei Gubarev <agubarev@users.noreply.github.com>

fix: a slightly changed signature of `impl From<String> for SafePassword` to be a bit more generic

---

src/hidden.rs
src/password.rs

Adds `reveal` method to make it clear what value used: hidden or inner.
Also other useful traits derived: `Default`, `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Hash`.
Since `Hidden` implements `Deref` it's not clear to see where hidden or revealed value used (for `Display` trait, for example).
This change makes access to the hidden value explicit.
Unit tests

feat: add reveal method to Hidden

---

Cargo.toml
src/hidden.rs
src/lib.rs
src/message_format.rs
src/password.rs
src/safe_array.rs

Some data, like cryptographic key material or passwords, needs special handling. Such data typically should:
- be zeroized when it goes out of scope
- never be displayed or written to debug logs
- not typically be accessed except by (mutable) reference
- have a strictly enforced type to avoid misuse
This PR updates the `Hidden` type to handle this kind of data in a generic way. Hidden types can be instantiated using any underlying type that implements `Zeroize` and an optional differentiated type created by a macro that enforces context and prevents misuse.
The hidden data is stored on the heap in a `Box` wrapper. This allows us to safely zeroize it on drop, and automatically prevents display and debug from revealing it unintentionally. Further, we only expose access to the data via …

feat: improve hidden data handling

---

Cargo.toml

As in the title. Bump the borsh for RUSTSEC-2023-0033

fix: bump borsh version

---

Cargo.toml

This reverts commit c189a00146ceecafee880ebf1336d5e157fd4c63.
This is because we've decided not to go through the process of updating core, and tari-crypto with changes to the borsh interface. The version bump didn't actually fix the rustsec issue, which we handled differently in the core repo. This bump can be reverted until we decide to commit to the interface changes.

chore: revert bump borsh version for rustsec-2023-0033 (#55)

---

CHANGELOG.md
Cargo.toml

* removed password error for safe password  ([58](https://github.com/tari-project/tari_utilities/issues/58)) ([c067263](https://github.com/tari-project/tari_utilities/commit/c06726322683c4671b93388b444d108103cd7b55))

chore: up version

---

src/byte_array.rs
src/encoding.rs
src/serde/hex.rs

Modifies the `ByteArray` trait by renaming `from_bytes` to `from_bytes_canonical` for clarity.
BREAKING CHANGE: Changes the `ByteArray` trait.

chore!: rename `from_bytes` to `from_canonical_bytes`

---

src/epoch_time.rs
src/fixed_set.rs
src/hex.rs

Removes an expect from to_hex
Adds a max len to to_hex.

chore: remove expect from to_hex

---

src/safe_array.rs

This PR makes the `PartialEq` implementation of `SafeArray` more idiomatic.

chore: improve constant-time equality

---

.github/workflows/source-cov.yml
test_coverage.sh

The source coverage script and workflow are slightly stale. This updates them to get 'em going again.

fix: update source coverage script
